require("basic")
require("plugins")
require("colorscheme")
require("mappings")
require("command")
-- require("ntree")
-- require("bar")
require("user")
-- require("complete")
require("lsp")
-- require("treesitter")
